# Generated by Django 5.0.1 on 2024-02-10 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_remove_customer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='name',
            field=models.CharField(default='user', max_length=200),
        ),
    ]
